### ISSUE TITLE
Set default row factory to `as_dict`

### ISSUE THREAD

**Issue by rbroth** [BritishGeologicalSurvey/etlhelper#153] opened 2023-04-24 14:49 UTC
(because dictionaries are more common and easier to use, with mutability built-in, and faster to build than named tuples).  Related to #132.

### Acceptance Criteria

- [x] The default row factory for all functions is set to `dict_row_factory`
- [ ] Tests are updated to account for this change
- [x] Documentation is updated

**Comment by rbroth** [comment] 2023-04-24 14:50
This will be a breaking change and the major version should be incremented when this merged into main

**Comment by leorudczenko** [comment] 2023-08-25 16:28
I've made the change to the default row factory for all functions in `etlhelper/etl.py`. I have also made changes to tests which were broken by the change. Due to connection problems on my end, I haven't been able to run the `mssql` tests. However, I can confirm that all of the other tests are now passing with the change.

**Comment by volcan01010** [comment] 2023-08-28 10:58
I'm updating this now.  There is a problem with the `msql` tests, in that the `fast_executemany` command that it uses behind the scenes wants a tuple as an input.

**Comment by volcan01010** [comment] 2023-08-28 14:40
Closing as it has now been merged into `for_v1`.

**Closed by volcan01010** 2023-08-28 14:40 UTC
