### ISSUE TITLE
Character '%'  cause an error

### ISSUE THREAD

**Issue by LuiguiSaenz** [BritishGeologicalSurvey/etlhelper#144] opened 2022-11-22 17:17 UTC
When the % character exists in the query to be executed as part of a string, the "execute" function throws the following error

  File "/home/luigui/Escritorio/repositorios/logros-backend/env/lib/python3.8/site-packages/etlhelper/etl.py", line 429, in execute
    cursor.execute(query, parameters)
IndexError: tuple index out of range

**Comment by volcan01010** [comment] 2022-12-16 16:24
Hi @LuiguiSaenz, do you have any more information that might help use track down the problem?

**Comment by LuiguiSaenz** [comment] 2022-12-17 14:25
when you use a like in the query, for example:
UPDATE TABLE
SET FIELD1='value'
WHERE CODIGO LIKE 'TN%'

**Comment by volcan01010** [comment] 2023-01-31 10:43
Can you give more information please, e.g. the full `execute` command that you are using and some example values for `query` and `parameters` that cause the problem?  I am not able to recreate your issue.

I wondered if the issue was with the logging system, as it can interpret `%` characters as placeholders.  But I ran your query against the logging that runs in [etlhelper.execute](https://github.com/BritishGeologicalSurvey/etlhelper/blob/887f0848f0d5f29f884b69aec30214b26b079e40/etlhelper/etl.py#L423) and it seems to work:

```python
>>> import logging
>>> logger = logging.getLogger()
>>> logging.basicConfig(level=logging.DEBUG)
>>> query = "UPDATE TABLE SET FIELD 1='value' WHERE CODIGO LIKE 'TN%'"
>>> parameters = ()
>>> conn = "my connection"
>>> logger.debug(f"Executing:\n\n{query}\n\nwith parameters:\n\n"
...              f"{parameters}\n\nagainst\n\n{conn}")
>>> logger.debug(f"Executing:\n\n{query}\n\nwith parameters:\n\n"
...              f"{parameters}\n\nagainst\n\n{conn}")
DEBUG:root:Executing:

UPDATE TABLE SET FIELD 1='value' WHERE CODIGO LIKE 'TN%'

with parameters:

()

against

my connection
```

**Comment by rbroth** [comment] 2023-04-24 14:51
Closing, because we can't reproduce the problem with the information provided

**Closed by rbroth** 2023-04-24 14:51 UTC
